services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: living_stage
      POSTGRES_PASSWORD: living_stage
      POSTGRES_DB: living_stage
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
